### ISSUE TITLE
Please explain how to use the "internal snippets"???

### ISSUE THREAD

**Issue by mattslay** [newdatasystems/vscode-foxpro#1]
Please explain how to use the "internal snippets"???

**Comment by newdatasystems** [comment]
You'd need to be using our internal VFP libraries which they reference.

There are two separate tools that we have internally:
dal/dao abstracts data access into objects (with a syntax kinda like Linq)
multiprompt is a dialog builder based on an internal dynamic UI toolkit for VFP

I haven't done anything to make them ready for release to the public.

**Comment by mattslay** [comment]
If it’s not part of the public tool, then you should remove it front the fro t page documentation. It’s confusing to people, as it was to me.

**Comment by newdatasystems** [comment]
moved to a collapsed element at the bottom
