### ISSUE TITLE
Add a screenshot to the home page of this extension...

### ISSUE THREAD

**Issue by mattslay** [newdatasystems/vscode-foxpro#2]
I think it would be cool if you added a screenshot of VFP code in VS Code on the home page of this extension in the Marketplace. It would look really cool!

Here is the code you can paste into your readme,md file to display the screenshot from my original repo:

`![alt text](http://content.screencast.com/users/MattSlay/folders/Snagit/media/354acc1a-ff2b-4514-84d0-3c47b2d7e250/04.01.2019-14.14.png "screenshot")
`

![alt text](http://content.screencast.com/users/MattSlay/folders/Snagit/media/354acc1a-ff2b-4514-84d0-3c47b2d7e250/04.01.2019-14.14.png "screenshot")

**Comment by mattslay** [comment]
here is the code you can past in your readme.md file to point to the screenshot image in my original repo:

![alt text](http://content.screencast.com/users/MattSlay/folders/Snagit/media/354acc1a-ff2b-4514-84d0-3c47b2d7e250/04.01.2019-14.14.png "screenshot")

**Comment by newdatasystems** [comment]
I added it to the github so the screenshot will be included in the next update. I'll leave the ticket open until I do.

**Comment by newdatasystems** [comment]
published as 1.4.5
