### ISSUE TITLE
Use the  green INSTALL button instead of the download link...

### ISSUE THREAD

**Issue by mattslay** [newdatasystems/vscode-foxpro#3]
Attention everyone - be sure to use the green INSTALL button at the top of the Visual Studio Code Marketplace page, rather than the "download" link on the right side bar of that page. The INSTALL button will launch VS Code for you and to the install, whereas the download link downloads a VSIX file, but will give an error if you click on the VSIX to install it.

Follow these instructions to install the VSIX from the VS Code IDE:
https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

Here is the error you will get with if you just click on the downloaded VSIX file to launch it from Windows Explorer:

![image](https://user-images.githubusercontent.com/309016/56058955-84d2e700-5d28-11e9-9f2f-23ad70c19a56.png)

**Comment by newdatasystems** [comment]
That's funny. I never tried installing it from VSIX. What do you think is causing that error? Maybe I have a bad dependency in my package.json file.

**Comment by mattslay** [comment]
You can use the VSIX, but you have to do it from within VS Code, whereas with Visual Studio, a VSIX can be installed by double clicking on it.

**Comment by newdatasystems** [comment]
I added some text and your link to the README.md file
