### ISSUE TITLE
EndDefine is the wrong color...

### ISSUE THREAD

**Issue by mattslay** [newdatasystems/vscode-foxpro#4]
Notice that **Define Class** is in blue, and so are **Procedure** and **End Procedure**, but see how **End Define** has a yellow color...

![image](https://user-images.githubusercontent.com/309016/56059471-c021e580-5d29-11e9-8802-bebbba44bdfa.png)

**Comment by newdatasystems** [comment]
published in 1.4.5

**Comment by mattslay** [comment]
I got the latest update in VS Code to 1.4.5, but i still have this same issue. Are you sure you got the code changed in this repo and in the tool in the Marketplace???

**Comment by newdatasystems** [comment]
dammit! lol

**Comment by newdatasystems** [comment]
Actually I was btten by the Git-monster. Forgot to push the commit. 

Just published 1.4.6

**Comment by mattslay** [comment]
It’s not a big issue but your changelog.md file shows 1.4.5 listed twice. The top most entry should read 1.4.6.
